"""Crear tabla de solicitudes

Revision ID: 50b4fb4e4bd8
Revises: 
Create Date: 2026-08-07 03:53:07.438398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50b4fb4e4bd8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitudes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identificador_externo', sa.String(), nullable=False),
    sa.Column('tipo_solicitud', sa.Enum('ACCESO_PLATAFORMA', 'SOPORTE_TECNICO', 'ACADEMICA', 'ADMINISTRATIVA', name='tiposolicitud'), nullable=False),
    sa.Column('nombre_solicitante', sa.String(), nullable=False),
    sa.Column('correo_electronico', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=False),
    sa.Column('prioridad', sa.Enum('BAJA', 'MEDIA', 'ALTA', name='prioridadsolicitud'), nullable=False),
    sa.Column('estado', sa.Enum('RECIBIDA', 'EN_PROCESO', 'COMPLETADA', 'RECHAZADA', name='estadosolicitud'), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solicitudes_estado'), 'solicitudes', ['estado'], unique=False)
    op.create_index(op.f('ix_solicitudes_id'), 'solicitudes', ['id'], unique=False)
    op.create_index(op.f('ix_solicitudes_identificador_externo'), 'solicitudes', ['identificador_externo'], unique=True)
    op.create_index(op.f('ix_solicitudes_prioridad'), 'solicitudes', ['prioridad'], unique=False)
    op.create_index(op.f('ix_solicitudes_tipo_solicitud'), 'solicitudes', ['tipo_solicitud'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_solicitudes_tipo_solicitud'), table_name='solicitudes')
    op.drop_index(op.f('ix_solicitudes_prioridad'), table_name='solicitudes')
    op.drop_index(op.f('ix_solicitudes_identificador_externo'), table_name='solicitudes')
    op.drop_index(op.f('ix_solicitudes_id'), table_name='solicitudes')
    op.drop_index(op.f('ix_solicitudes_estado'), table_name='solicitudes')
    op.drop_table('solicitudes')
    # ### end Alembic commands ###
